version: '2'
services:
  transmission:
    image: haugene/transmission-openvpn:latest
    container_name: transmission
    volumes:
      # - /etc/localtime:/etc/localtime:ro
      - ${TRANSMISSION_HOME}:/data
      - ${TRANSMISSION_DOWNLOAD_DIR}:/downloads
      - ./openvpn/vpnunlimited/:/etc/openvpn/vpnunlimited
    ports:
      - ${TRANSMISSION_PORT}:9091
    environment:
      - OPENVPN_PROVIDER=${OPENVPN_PROVIDER}
      - OPENVPN_CONFIG=${OPENVPN_CONFIG}
      - OPENVPN_USERNAME=${OPENVPN_USERNAME}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
      - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
      - LOCAL_NETWORK=${LOCAL_NETWORK}
    dns:
      - 8.8.8.8
      - 8.8.4.4
    restart: always
    privileged: true